### PR TITLE
use names in getPackageRecords, avoid returning duplicates

### PR DESCRIPTION
**Pull request by krlmlr**
This is a first step towards #224, I hope this will allow implementing the cache while keeping the vectorized nature of getPackageRecords. It works by giving names to `pkgNames` which are then propagated to `allRecords`. As a bonus, `allRecords` is reordered in the order of `pkgNames`. If this introduces errors, they are not caught by the tests.

If the naming fails to carry through, would a warning/error be appropriate here?

What is a good place for `vecdiff`?

### CODE REVIEW

**Comment by kevinushey** [comment]
I think it's okay to leave `vecdiff` there, although it could also fit in `utils.R` (either is fine to me).

That said, I don't quite understand directly from reading the code -- what is the gain of changing from `setdiff` to `vecdiff`?

**Comment by krlmlr** [comment]
I can insert a second `dropNull` if this is a valid condition. Is it? I thought that it's [an error](https://github.com/rstudio/packrat/pull/226/files#diff-248d140618b0a0963077f113fa13f3b8L214) if there's no package record to a queried package, but then I don't know the implementation well enough.

We might rather want to look for empty names in `allRecords` -- shall we warn or fail in this case? (A failure in such a case indicates an implementation error.)

`vecdiff` keeps names, `setdiff` doesn't (due to the call to `unique`). Will move to `utils.R`.

**Comment by krlmlr** [comment]
I have moved `vecdiff()` to `utils.R`, but I'm still unsure what to do if the names in `allRecords` for some reason don't refer to valid package names, or if no package record has been found for a package. (The former might indicate an implementation error, the latter might be a regular error condition or could be simply ignored.)

**Comment by krlmlr** [comment]
Merged with master.

**Comment by kevinushey** [comment]
@krlmlr sorry it's taken so long to review + get back to this. This change looks good to me; I'll merge now.

**Pull request merged**
