### PR TITLE
addresses #458 slow snapshot

### PR DESCRIPTION
**Pull request by ras44**
This PR adds a `fileDependencies.Rmd.evaluate` option (default TRUE) to choose whether or not to recursively search for dependencies in R Markdown documents.

### CODE REVIEW

**Comment by kevinushey** [comment]
I would prefer having this as an R-level option rather than a project-level option, just because I think this will ultimately be fixed one way or another in Packrat and the option will ultimately be obviated.

**Comment by kevinushey** [comment]
(that is, unless there's a strong reason why this needs to be a project option)

**Comment by ras44** [comment]
sounds good, I've updated both PRs with R-level option

**Comment by ras44** [comment]
closing in favor of #513

**Pull request closed without merging**
