### PR TITLE
Allow empty repository field

### PR DESCRIPTION
**Pull request by kenahoo**
Addresses issue #528

### CODE REVIEW

**Comment by kenahoo** [comment]
I'm not sure what the test failures are about - in my local environment, a huge number of tests fail spectacularly both before & after the patch so I'm not sure if the new code is responsible for it or not.

**Comment by kevinushey** [comment]
I'll try to review and figure out what's going on next week.

**Comment by kenahoo** [comment]
Thanks, appreciated.

**Comment by kevinushey** [comment]
Hi @kenahoo -- thanks for your patience. This PR looks good to me, and I think the Travis failures are unrelated.

For contributions to RStudio's open source projects, we do require a [contributor license agreement](https://www.rstudio.com/wp-content/uploads/2014/06/RStudioIndividualContributorAgreement.pdf) -- would you mind filling that out and sending it to the e-mail indicated in the form?

Once we have that on file I'll be happy to merge this PR. Thanks!

**Comment by kenahoo** [comment]
@kevinushey Sure, I can do that - I thought I'd done this before, though, any way to check whether I'm already "in the system"?

**Comment by kevinushey** [comment]
We do maintain a database of signed CLAs, but I didn't see your name in there -- if you have signed one before and it just wasn't added for some reason, I apologize. Would you be willing to file a new one in any case?

**Comment by kenahoo** [comment]
Yup - just making sure I push it through the right channels at my company, I hope to have it back today or tomorrow.

**Comment by kevinushey** [comment]
Sounds good -- thanks for your patience.

**Comment by kenahoo** [comment]
Hey @kevinushey , I think we probably want to use the https://www.rstudio.com/wp-content/uploads/2014/06/RStudioCorporateContributorAgreement.pdf in this case, since I did this on "company time" while working on some deployment stuff for an internal application, sound correct?  Company is NextEra Analytics (formerly known as WindLogics).

**Comment by kevinushey** [comment]
That sounds correct to me.

**Comment by kenahoo** [comment]
I've sent the signed agreement document to JJ.

**Comment by kevinushey** [comment]
Thanks! We've received the CLA; I'll merge this now.

**Pull request merged**
