### PR TITLE
option setting does not modify other options

### LINKED ISSUE #655: option setters clear other settings
Using the option setter clears other configured options.

```
packrat::set_opts(ignored.packages = c("emo"), persist = FALSE)
packrat::opts$snapshot.recommended.packages(TRUE, persist = FALSE)
packrat::get_opts(c("ignored.packages"))
# => NULL
```

This is using the setter defined by:

https://github.com/rstudio/packrat/blob/c648ce2fb915289d3de5c58eae9b15202a839163/R/options.R#L173-L179

the setter is connected to the `packrat::opts` here:

https://github.com/rstudio/packrat/blob/c648ce2fb915289d3de5c58eae9b15202a839163/R/options.R#L221-L223

### PR DESCRIPTION
**Pull request by aronatkins**
fixes #655

### CODE REVIEW

**Review by kevinushey — APPROVED** [review]
LGTM! Thanks for adding a test as well.

**Comment by toph-allen** [comment]
#### What I did

I smoke tested this and #654 in a merged branch.

I tested the changes by:
- initializing Packrat in a test repo (using `external.packages = "packrat"`, which I assume is a requirement for working with local branches);
- running `packrat:::appDependencies(".")` and `reconnect::writeManifest()` before and after running `packrat::set_opts(ignored.packages = c("emo", "Rcpp", "stringr"))`;
- running a few other packrat functions.

Specific to this change, I also ran the snippet of code from Aron's issue:

```r
packrat::set_opts(ignored.packages = c("emo"), persist = FALSE)
packrat::opts$snapshot.recommended.packages(TRUE, persist = FALSE)
packrat::get_opts(c("ignored.packages"))
```

#### Results

The code snippet from Aron's issue performed as expected.

`reconnect::writeManifest()` correctly ignored packages. Previously, because of option-modification that package was performing, Packrat settings were lost, so the correct behavior indicates the change is working correctly.

I noticed that when the `ignored.packages` option was absent (i.e. `packrat.set_opts(ignored.packages = "")`), all the entries in the manifest had the following fields:

```
      "Repository": "https://cran.rstudio.com/",
      "GithubRepo": null,
      "GithubUsername": null,
      "GithubRef": null,
      "GithubSha1": null,
```

With `packrat.set_opts(ignored.packages = c("emo", "Rcpp", "stringr")`, those fields were missing.

I performed the same check with a build of Packrat only from this branch, not from the combined branch, and the same change occurred. I'm not sure if this is expected, or problematic, so I figured I'd raise it here. The manifests are attached to this comment (with their file extension changed to `.txt`, because GitHub doesn't allow `.json` attachments, I guess).

[manifest-655-ignore.txt](https://github.com/rstudio/packrat/files/8043118/manifest-655-ignore.txt)
[manifest-655-no-ignore.txt](https://github.com/rstudio/packrat/files/8043119/manifest-655-no-ignore.txt)

**Comment by aronatkins** [comment]
The GitHub fields are probably a result of using a data frame to record all the dependencies; once one record requires a field, they all receive that value. 

@toph-allen - Could you file an rsconnect issue to track the presence of those null-value fiends? They're harmless, but maybe worth trimming.

**Comment by toph-allen** [comment]
That makes total sense as to the cause.

I'll add it to my list of issues to file :)

**Pull request merged**
